CREATE OR REPLACE FUNCTION disable_all_rls()
RETURNS VOID AS $$
BEGIN
  ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
  ALTER TABLE IF EXISTS subscriptions DISABLE ROW LEVEL SECURITY;
  ALTER TABLE IF EXISTS usage_stats DISABLE ROW LEVEL SECURITY;
  ALTER TABLE IF EXISTS responses DISABLE ROW LEVEL SECURITY;
  ALTER TABLE IF EXISTS feedback DISABLE ROW LEVEL SECURITY;
  ALTER TABLE IF EXISTS questions DISABLE ROW LEVEL SECURITY;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
